kind: pipeline
name: test-on-amd64

platform:
  arch: amd64

steps:
- name: test
  image: python:3.7
  commands:
    - "echo arch: $(uname -m)"
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pytest -v --cov --cov-report=term --cov-report=xml
  when:
    event:
      - push
      - pull_request
- name: coverage
  image: plugins/codecov
  settings:
    token:
      from-secret: codecov-token
    files:
     - coverage.xml

---

kind: pipeline
name: test-on-arm

platform:
  arch: arm

steps:
- name: test
  image: python:3.7
  commands:
    - "echo arch: $(uname -m)"
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pytest -v
  when:
    event:
      - push
      - pull_request

---

kind: pipeline
name: test-on-arm64

platform:
  arch: arm64

steps:
- name: test
  image: python:3.7
  commands:
    - "echo arch: $(uname -m)"
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pytest -v
  when:
    event:
      - push
      - pull_request
