kind: pipeline
name: amd64-python37

platform:
  arch: amd64

steps:
- name: test
  image: python:3.7
  commands:
    - "echo arch: $(uname -m)"
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pytest -v --cov --cov-report=term --cov-report=xml
  when:
    event:
      - push
      - pull_request
- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov-token
    files:
     - coverage.xml
- name: build docker image
  image: plugins/docker
  settings:
    username: heavenbot
    repo: heavenbot/heavenbot
    password:
      from_secret: dockerhub-password

---

kind: pipeline
name: amd64-python36

platform:
  arch: amd64

steps:
- name: test
  image: python:3.6
  commands:
    - "echo arch: $(uname -m)"
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pytest -v
  when:
    event:
      - push
      - pull_request

---

kind: pipeline
name: arm

platform:
  arch: arm

steps:
- name: test
  image: python:3.7
  commands:
    - "echo arch: $(uname -m)"
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pytest -v
  when:
    event:
      - push
      - pull_request
- name: build docker image
  image: plugins/docker
  settings:
    username: heavenbot
    repo: heavenbot/heavenbot
    password:
      from_secret: dockerhub-password

---

kind: pipeline
name: arm64

platform:
  arch: arm64

steps:
- name: test
  image: python:3.7
  commands:
    - "echo arch: $(uname -m)"
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pytest -v
  when:
    event:
      - push
      - pull_request
- name: build docker image
  image: plugins/docker
  settings:
    username: heavenbot
    repo: heavenbot/heavenbot
    password:
      from_secret: dockerhub-password
